name: Build and push image

on:
  push:
    paths:
      - 'atomic/**'
      - '.github/workflows/atomic.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    container:
      image: registry.fedoraproject.org/fedora:${{ vars.RELEASEVER }}
      options: --privileged --volume /:/run/host:rw
    env:
      IMAGENAME: ghcr.io/${{ github.repository }}/kde-unstable

    steps:
      - name: Reclaim disk space
        run: |
          rm -rf /run/host/usr/local/lib/android /run/host/usr/share/dotnet /run/host/opt/ghc /run/host/opt/hostedtoolcac

      - name: Prepare
        run: |
          dnf -y up && dnf -y install \
            bsdtar \
            buildah \
            dbus-daemon \
            distribution-gpg-keys \
            file \
            git-core \
            jq \
            ostree \
            podman \
            rpm-ostree \
            selinux-policy-targeted \
            skopeo \
            tar \
            zstd
          cat << EOF > /etc/containers/registries.d/sigstore.yaml
          docker:
            $IMAGENAME:
              use-sigstore-attachments: true
          EOF
          cp /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-$(rpm -E %fedora) /etc/pki/rpm-gpg/
          cp /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$(rpm -E %fedora) /etc/pki/rpm-gpg/
          dnf clean all

      - uses: actions/checkout@v4

      - name: Fix path
        run: |
          sed -i "s|@@REPO@@|$IMAGENAME|" atomic/sigstore.yaml

      - name: Get buildid
        id: get-buildid
        run: |
          echo "buildid=$(date -u "+%Y%m%d.%H%M")" >> $GITHUB_OUTPUT

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: atomic/buildcache.tar.zst
          key: build-${{ steps.get-buildid.outputs.buildid }}
          restore-keys: build-

      - name: Build
        id: build
        run: |
          pushd atomic > /dev/null || exit 1
          if [[ -f "buildcache.tar.zst" ]]; then
            bsdtar --acls --xattrs -xpzf buildcache.tar.zst
            rm buildcache.tar.zst
          fi
          mkdir -p cache

          version="$(rpm-ostree compose tree --print-only kinoite.yaml | jq -r '."mutate-os-release"')"
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "Composing kinoite ${version}.${{ steps.get-buildid.outputs.buildid }} ..."

          rpm-ostree compose rootfs --cachedir=cache kinoite.yaml rootfs
          rpm-ostree compose build-chunked-oci --bootc --format-version=1 \
            --max-layers 99 --rootfs=rootfs \
            --output containers-storage:localhost/kinoite:build

      - name: Key
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_PASSPHRASE: ${{ secrets.SIGN_PASSPHRASE }}
        run: |
          pushd atomic > /dev/null || exit 1
          echo "$SIGN_KEY" > ${{ github.repository_owner }}.private
          echo "$SIGN_PASSPHRASE" > ${{ github.repository_owner }}.passphrase

      - name: Push
        env:
          SKOPEO_ARGS: "--sign-by-sigstore-private-key ${{ github.repository_owner }}.private --sign-passphrase-file ${{ github.repository_owner }}.passphrase --retry-times 3 --dest-compress-format zstd"
        run: |
          skopeo login --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io

          pushd atomic > /dev/null || exit 1
          skopeo copy ${SKOPEO_ARGS} \
            "containers-storage:localhost/kinoite:build" \
            "docker://${IMAGENAME}:${{ steps.build.outputs.version }}.${{ steps.get-buildid.outputs.buildid }}"

          skopeo copy ${SKOPEO_ARGS} \
            "docker://${IMAGENAME}:${{ steps.build.outputs.version }}.${{ steps.get-buildid.outputs.buildid }}" \
            "docker://${IMAGENAME}:${{ steps.build.outputs.version }}"

      - name: Compress the cache directory manually to preserve xattrs
        run: |
          pushd atomic > /dev/null || exit 1
          bsdtar --zstd --options zstd:compression-level=17,zstd:threads=0 --acls --xattrs -cpaf buildcache.tar.zst cache

      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: atomic/buildcache.tar.zst
          key: ${{ steps.cache.outputs.cache-primary-key }}
