name: Build and push image

on:
  push:
    paths:
      - 'atomic/**'
      - '.github/workflows/atomic.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - rawhide
          - 43
          - 42
    container:
      image: registry.fedoraproject.org/fedora:${{ matrix.version }}
      options: --privileged --volume /:/run/host:rw
    env:
      IMAGENAME: ghcr.io/${{ github.repository }}/kde-unstable

    steps:
      - name: Reclaim disk space
        run: |
          rm -rf /run/host/usr/local/lib/android /run/host/usr/share/dotnet /run/host/opt/ghc /run/host/opt/hostedtoolcache

      - name: Prepare
        run: |
          dnf -y up && dnf -y install \
            bsdtar \
            buildah \
            dbus-daemon \
            distribution-gpg-keys \
            file \
            git-core \
            jq \
            ostree \
            podman \
            rpm-ostree \
            selinux-policy-targeted \
            skopeo \
            tar \
            zstd
          cat << EOF > /etc/containers/registries.d/sigstore.yaml
          docker:
            $IMAGENAME:
              use-sigstore-attachments: true
          EOF
          dnf clean all

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Prepare
        run: |
          sed -i "s|@@REPO@@|$IMAGENAME|" atomic/sigstore.yaml
          if [[ "${{ matrix.version }}" == "rawhide" ]]; then
            version="44"
            sed -i "s/\$releasever/rawhide/" atomic/coprs.repo
          else
            version="${{ matrix.version }}"
          fi
          if [[ "${{ matrix.version }}" == "rawhide" ]]; then
            sed -i '/shim-ia32/d' atomic/common.yaml
          fi
          if [[ "${{ matrix.version }}" == "rawhide" || "${{ matrix.version }}" == "43" ]]; then
            sed -i '/basesystem/d' atomic/common-packages.yaml
            sed -i '/pipewire-alsa/a\  - pipewire-config-raop' atomic/common-packages.yaml
          fi
          sed -i "s/^releasever:.*/releasever: ${version}/" atomic/common.yaml
          sed -i "/^ref/s/[[:digit:]]\+/${version}/" atomic/kinoite-common.yaml

      - name: Figure out version
        id: buildid
        run: |
          pushd atomic > /dev/null || exit 1
          date_now="$(date -u "+%Y%m%d")"
          if [[ "${{ matrix.version }}" == "rawhide" ]]; then
            fedora_version="rawhide"
          else
            fedora_version="$(rpm-ostree compose tree --print-only kinoite.yaml | jq -r '."mutate-os-release"')"
          fi
          version_remote="$(skopeo inspect "docker://${IMAGENAME}:${fedora_version}" | jq -r '.Labels."org.opencontainers.image.version"' || :)"
          if [[ -n "${version_remote}" ]]; then
            date_remote="${version_remote%\.*}"
            date_remote="${date_remote#*\.}"
          fi
          if [[ "${date_now}" == "${date_remote}" ]]; then
            patch="${version_remote##*\.}"
            ((patch++)) || true
            buildid="${date_now}.${patch}"
          else
            buildid="${date_now}.0"
          fi

          sed "s/@@VER_TO_REPLACE@@/${date_now}.0/" -i common.yaml
          sed "s/@@IMAGE_VERSION@@/${buildid}/" -i common.yaml

          echo "fedora_version=${fedora_version}" >> $GITHUB_OUTPUT
          echo "buildid=${buildid}" >> $GITHUB_OUTPUT

      # - name: Restore cache
      #   id: cache
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: atomic/buildcache.tar.zst
      #     key: build-${{ steps.get-buildid.outputs.buildid }}
      #     restore-keys: build-

      - name: Build
        run: |
          pushd atomic > /dev/null || exit 1
          if [[ -f "buildcache.tar.zst" ]]; then
            bsdtar --acls --xattrs -xpzf buildcache.tar.zst
            rm buildcache.tar.zst
          fi
          mkdir -p cache

          echo "Composing kinoite ${{ steps.buildid.outputs.fedora_version }}.${{ steps.buildid.outputs.buildid }} ..."

          rpm-ostree compose image \
            --cachedir=cache \
            --initialize \
            --max-layers 96 \
            --format oci \
            --label="org.opencontainers.image.version=${{ steps.buildid.outputs.fedora_version }}.${{ steps.buildid.outputs.buildid }}" \
            "kinoite.yaml" \
            "kinoite-build"

      - name: Key
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_PASSPHRASE: ${{ secrets.SIGN_PASSPHRASE }}
        run: |
          pushd atomic > /dev/null || exit 1
          echo "$SIGN_KEY" > ${{ github.repository_owner }}.private
          echo "$SIGN_PASSPHRASE" > ${{ github.repository_owner }}.passphrase

      - name: Push
        env:
          SKOPEO_ARGS: "--sign-by-sigstore-private-key ${{ github.repository_owner }}.private --sign-passphrase-file ${{ github.repository_owner }}.passphrase --retry-times 3 --dest-compress-format zstd"
        run: |
          skopeo login --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io

          pushd atomic > /dev/null || exit 1
          for i in {1..5}; do
            skopeo copy ${SKOPEO_ARGS} \
              "oci:kinoite-build" \
              "docker://${IMAGENAME}:${{ steps.buildid.outputs.fedora_version }}.${{ steps.buildid.outputs.buildid }}" && break || sleep $((5 * i))
          done

          for i in {1..5}; do
            skopeo copy ${SKOPEO_ARGS} \
              "docker://${IMAGENAME}:${{ steps.buildid.outputs.fedora_version }}.${{ steps.buildid.outputs.buildid }}" \
              "docker://${IMAGENAME}:${{ steps.buildid.outputs.fedora_version }}" && break || sleep $((5 * i))
          done

          if [[ "${{ steps.buildid.outputs.fedora_version }}" == "${{ vars.RELEASEVER }}" ]]; then
            for i in {1..5}; do
              skopeo copy ${SKOPEO_ARGS} \
                "docker://${IMAGENAME}:${{ steps.buildid.outputs.fedora_version }}.${{ steps.buildid.outputs.buildid }}" \
                "docker://${IMAGENAME}:latest" && break || sleep $((5 * i))
            done
          fi

      # - name: Compress the cache directory manually to preserve xattrs
      #   run: |
      #     pushd atomic > /dev/null || exit 1
      #     bsdtar --zstd --options zstd:compression-level=17,zstd:threads=0 --acls --xattrs -cpaf buildcache.tar.zst cache

      # - name: Save cache
      #   id: cache-save
      #   uses: actions/cache/save@v4
      #   with:
      #     path: atomic/buildcache.tar.zst
      #     key: ${{ steps.cache.outputs.cache-primary-key }}
