name: Bump revisions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    container:
      image: ghcr.io/solopasha/kde6-copr/buildroot:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Branch
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          branch="update-$(date +%Y%m%d)"
          echo "branch=${branch}" >> $GITHUB_ENV
          git checkout -b "${branch}"

      - name: Bump revisions
        run: |
          bash bumpall.sh -g

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -- '*.spec' || exit 0
          git commit -m "bump revisions" || exit 0
          git push origin "${branch}"
          gh pr create --base unstable \
            --head "${branch}" --title "Bump revisions" \
            --body "This is an autogenerated PR" \
            --label autogenerated
