name: Build packages

on:
  workflow_call:
    secrets:
      gpgkey:
        required: true
      copr_webhook:
        required: true
      copr_webhook_beta:
        required: true
    inputs:
      specfiles:
        required: false
        type: string
      abidiff:
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  changed-files:
    name: Assemble builds
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      modified_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed specs
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: |
            **/*.spec

  aurorae:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/aurorae.spec') ||
          contains(inputs.specfiles, '/aurorae.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kdecoration
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/aurorae/aurorae.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  bluedevil:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/bluedevil.spec') ||
          contains(inputs.specfiles, '/bluedevil.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/bluedevil/bluedevil.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  breeze-gtk:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/breeze-gtk.spec') ||
          contains(inputs.specfiles, '/breeze-gtk.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-breeze
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/breeze-gtk/breeze-gtk.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  flatpak-kcm:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/flatpak-kcm.spec') ||
          contains(inputs.specfiles, '/flatpak-kcm.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/flatpak-kcm/flatpak-kcm.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  grub2-breeze-theme:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/grub2-breeze-theme.spec') ||
          contains(inputs.specfiles, '/grub2-breeze-theme.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/grub2-breeze-theme/grub2-breeze-theme.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      debuginfo: false
      abidiff: ${{ inputs.abidiff }}

  kactivitymanagerd:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kactivitymanagerd.spec') ||
          contains(inputs.specfiles, '/kactivitymanagerd.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kactivitymanagerd/kactivitymanagerd.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kcm_wacomtablet:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kcm_wacomtablet.spec') ||
          contains(inputs.specfiles, '/kcm_wacomtablet.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
      - plasma5support
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kcm_wacomtablet/kcm_wacomtablet.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kde-cli-tools:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kde-cli-tools.spec') ||
          contains(inputs.specfiles, '/kde-cli-tools.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-workspace
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kde-cli-tools/kde-cli-tools.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kde-gtk-config:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kde-gtk-config.spec') ||
          contains(inputs.specfiles, '/kde-gtk-config.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kdecoration
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kde-gtk-config/kde-gtk-config.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kdecoration:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kdecoration.spec') ||
          contains(inputs.specfiles, '/kdecoration.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kdecoration/kdecoration.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kdeplasma-addons:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kdeplasma-addons.spec') ||
          contains(inputs.specfiles, '/kdeplasma-addons.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kdeplasma-addons/kdeplasma-addons.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kgamma:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kgamma.spec') ||
          contains(inputs.specfiles, '/kgamma.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kgamma/kgamma.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kglobalacceld:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kglobalacceld.spec') ||
          contains(inputs.specfiles, '/kglobalacceld.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kglobalacceld/kglobalacceld.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kinfocenter:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kinfocenter.spec') ||
          contains(inputs.specfiles, '/kinfocenter.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kinfocenter/kinfocenter.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kmenuedit:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kmenuedit.spec') ||
          contains(inputs.specfiles, '/kmenuedit.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kmenuedit/kmenuedit.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  knighttime:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/knighttime.spec') ||
          contains(inputs.specfiles, '/knighttime.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/knighttime/knighttime.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kpipewire:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kpipewire.spec') ||
          contains(inputs.specfiles, '/kpipewire.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kpipewire/kpipewire.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  krdp:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/krdp.spec') ||
          contains(inputs.specfiles, '/krdp.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kpipewire
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/krdp/krdp.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kscreen:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kscreen.spec') ||
          contains(inputs.specfiles, '/kscreen.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - layer-shell-qt
      - libkscreen
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kscreen/kscreen.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kscreenlocker:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kscreenlocker.spec') ||
          contains(inputs.specfiles, '/kscreenlocker.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - layer-shell-qt
      - libkscreen
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kscreenlocker/kscreenlocker.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  ksshaskpass:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/ksshaskpass.spec') ||
          contains(inputs.specfiles, '/ksshaskpass.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/ksshaskpass/ksshaskpass.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  ksystemstats:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/ksystemstats.spec') ||
          contains(inputs.specfiles, '/ksystemstats.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libksysguard
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/ksystemstats/ksystemstats.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kwayland:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kwayland.spec') ||
          contains(inputs.specfiles, '/kwayland.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kwayland/kwayland.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kwayland-integration:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kwayland-integration.spec') ||
          contains(inputs.specfiles, '/kwayland-integration.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kwayland-integration/kwayland-integration.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kwin:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kwin.spec') ||
          contains(inputs.specfiles, '/kwin.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kdecoration
      - kglobalacceld
      - knighttime
      - kscreenlocker
      - kwayland
      - libplasma
      - plasma-activities
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kwin/kwin.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kwin-x11:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kwin-x11.spec') ||
          contains(inputs.specfiles, '/kwin-x11.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kdecoration
      - kglobalacceld
      - knighttime
      - kscreenlocker
      - libplasma
      - plasma-activities
      - plasma-breeze
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kwin-x11/kwin-x11.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kwrited:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kwrited.spec') ||
          contains(inputs.specfiles, '/kwrited.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/kwrited/kwrited.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  layer-shell-qt:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/layer-shell-qt.spec') ||
          contains(inputs.specfiles, '/layer-shell-qt.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/layer-shell-qt/layer-shell-qt.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkscreen:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkscreen.spec') ||
          contains(inputs.specfiles, '/libkscreen.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/libkscreen/libkscreen.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libksysguard:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libksysguard.spec') ||
          contains(inputs.specfiles, '/libksysguard.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/libksysguard/libksysguard.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libplasma:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libplasma.spec') ||
          contains(inputs.specfiles, '/libplasma.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-activities
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/libplasma/libplasma.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  ocean-sound-theme:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/ocean-sound-theme.spec') ||
          contains(inputs.specfiles, '/ocean-sound-theme.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/ocean-sound-theme/ocean-sound-theme.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  oxygen-sounds:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/oxygen-sounds.spec') ||
          contains(inputs.specfiles, '/oxygen-sounds.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/oxygen-sounds/oxygen-sounds.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  pam-kwallet:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/pam-kwallet.spec') ||
          contains(inputs.specfiles, '/pam-kwallet.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/pam-kwallet/pam-kwallet.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-activities:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-activities.spec') ||
          contains(inputs.specfiles, '/plasma-activities.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-activities/plasma-activities.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-activities-stats:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-activities-stats.spec') ||
          contains(inputs.specfiles, '/plasma-activities-stats.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-activities
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-activities-stats/plasma-activities-stats.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-breeze:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-breeze.spec') ||
          contains(inputs.specfiles, '/plasma-breeze.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kdecoration
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-breeze/plasma-breeze.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-browser-integration:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-browser-integration.spec') ||
          contains(inputs.specfiles, '/plasma-browser-integration.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-activities
      - plasma-workspace
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-browser-integration/plasma-browser-integration.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-desktop:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-desktop.spec') ||
          contains(inputs.specfiles, '/plasma-desktop.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kpipewire
      - kscreenlocker
      - kwin
      - libksysguard
      - libplasma
      - PackageKit-Qt
      - plasma5support
      - plasma-activities
      - plasma-activities-stats
      - plasma-workspace
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-desktop/plasma-desktop.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-discover:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-discover.spec') ||
          contains(inputs.specfiles, '/plasma-discover.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - PackageKit-Qt
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-discover/plasma-discover.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-disks:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-disks.spec') ||
          contains(inputs.specfiles, '/plasma-disks.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-disks/plasma-disks.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-drkonqi:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-drkonqi.spec') ||
          contains(inputs.specfiles, '/plasma-drkonqi.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-drkonqi/plasma-drkonqi.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-firewall:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-firewall.spec') ||
          contains(inputs.specfiles, '/plasma-firewall.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-firewall/plasma-firewall.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-integration:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-integration.spec') ||
          contains(inputs.specfiles, '/plasma-integration.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kwayland
      - plasma-breeze
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-integration/plasma-integration.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-milou:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-milou.spec') ||
          contains(inputs.specfiles, '/plasma-milou.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-milou/plasma-milou.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-nano:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-nano.spec') ||
          contains(inputs.specfiles, '/plasma-nano.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kwayland
      - kwin
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-nano/plasma-nano.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-nm:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-nm.spec') ||
          contains(inputs.specfiles, '/plasma-nm.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-nm/plasma-nm.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-oxygen:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-oxygen.spec') ||
          contains(inputs.specfiles, '/plasma-oxygen.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kdecoration
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-oxygen/plasma-oxygen.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-pa:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-pa.spec') ||
          contains(inputs.specfiles, '/plasma-pa.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-pa/plasma-pa.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-print-manager:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-print-manager.spec') ||
          contains(inputs.specfiles, '/plasma-print-manager.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-print-manager/plasma-print-manager.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-sdk:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-sdk.spec') ||
          contains(inputs.specfiles, '/plasma-sdk.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
      - plasma5support
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-sdk/plasma-sdk.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-systemmonitor:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-systemmonitor.spec') ||
          contains(inputs.specfiles, '/plasma-systemmonitor.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libksysguard
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-systemmonitor/plasma-systemmonitor.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-systemsettings:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-systemsettings.spec') ||
          contains(inputs.specfiles, '/plasma-systemsettings.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - plasma-activities
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-systemsettings/plasma-systemsettings.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-thunderbolt:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-thunderbolt.spec') ||
          contains(inputs.specfiles, '/plasma-thunderbolt.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-thunderbolt/plasma-thunderbolt.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-vault:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-vault.spec') ||
          contains(inputs.specfiles, '/plasma-vault.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libksysguard
      - libplasma
      - plasma-activities
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-vault/plasma-vault.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-welcome:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-welcome.spec') ||
          contains(inputs.specfiles, '/plasma-welcome.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libplasma
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-welcome/plasma-welcome.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-workspace:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-workspace.spec') ||
          contains(inputs.specfiles, '/plasma-workspace.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - knighttime
      - kscreenlocker
      - kwayland
      - kwin
      - layer-shell-qt
      - libkscreen
      - libksysguard
      - libplasma
      - PackageKit-Qt
      - plasma5support
      - plasma-activities
      - plasma-activities-stats
      - plasma-breeze
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-workspace/plasma-workspace.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-workspace-wallpapers:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-workspace-wallpapers.spec') ||
          contains(inputs.specfiles, '/plasma-workspace-wallpapers.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma-workspace-wallpapers/plasma-workspace-wallpapers.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma5support:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma5support.spec') ||
          contains(inputs.specfiles, '/plasma5support.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libksysguard
      - libplasma
      - plasma-activities
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plasma5support/plasma5support.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plymouth-kcm:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plymouth-kcm.spec') ||
          contains(inputs.specfiles, '/plymouth-kcm.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plymouth-kcm/plymouth-kcm.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plymouth-theme-breeze:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plymouth-theme-breeze.spec') ||
          contains(inputs.specfiles, '/plymouth-theme-breeze.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/plymouth-theme-breeze/plymouth-theme-breeze.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  polkit-kde:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/polkit-kde.spec') ||
          contains(inputs.specfiles, '/polkit-kde.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/polkit-kde/polkit-kde.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  powerdevil:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/powerdevil.spec') ||
          contains(inputs.specfiles, '/powerdevil.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - libkscreen
      - libplasma
      - plasma-activities
      - plasma-wayland-protocols
      - plasma-workspace
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/powerdevil/powerdevil.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  qqc2-breeze-style:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/qqc2-breeze-style.spec') ||
          contains(inputs.specfiles, '/qqc2-breeze-style.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/qqc2-breeze-style/qqc2-breeze-style.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  sddm-kcm:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/sddm-kcm.spec') ||
          contains(inputs.specfiles, '/sddm-kcm.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/sddm-kcm/sddm-kcm.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  spectacle:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/spectacle.spec') ||
          contains(inputs.specfiles, '/spectacle.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kpipewire
      - layer-shell-qt
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/spectacle/spectacle.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  xdg-desktop-portal-kde:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/xdg-desktop-portal-kde.spec') ||
          contains(inputs.specfiles, '/xdg-desktop-portal-kde.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kwayland
      - plasma-wayland-protocols
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./plasma/xdg-desktop-portal-kde/xdg-desktop-portal-kde.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  PackageKit-Qt:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/PackageKit-Qt.spec') ||
          contains(inputs.specfiles, '/PackageKit-Qt.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./related/PackageKit-Qt/PackageKit-Qt.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  plasma-wayland-protocols:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/plasma-wayland-protocols.spec') ||
          contains(inputs.specfiles, '/plasma-wayland-protocols.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
      copr_webhook: ${{ secrets.copr_webhook }}
      copr_webhook_beta: ${{ secrets.copr_webhook_beta }}
    with:
      spec: ./related/plasma-wayland-protocols/plasma-wayland-protocols.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

