name: Build packages

on:
  workflow_call:
    secrets:
      gpgkey:
        required: true
    inputs:
      specfiles:
        required: false
        type: string
      abidiff:
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  changed-files:
    name: Assemble builds
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      modified_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed specs
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: |
            **/*.spec

  akonadi-calendar:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/akonadi-calendar.spec') ||
          contains(inputs.specfiles, '/akonadi-calendar.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-contacts
      - akonadi-mime
      - akonadi-server
      - changed-files
      - kcalutils
      - kidentitymanagement
      - kmailtransport
      - kmime
      - libkleo
      - messagelib
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/akonadi-calendar/akonadi-calendar.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  akonadi-contacts:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/akonadi-contacts.spec') ||
          contains(inputs.specfiles, '/akonadi-contacts.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-server
      - changed-files
      - grantleetheme
      - kmime
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/akonadi-contacts/akonadi-contacts.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  akonadi-import-wizard:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/akonadi-import-wizard.spec') ||
          contains(inputs.specfiles, '/akonadi-import-wizard.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-server
      - changed-files
      - kidentitymanagement
      - kmailtransport
      - mailcommon
      - mailimporter
      - messagelib
      - pimcommon
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/akonadi-import-wizard/akonadi-import-wizard.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  akonadi-mime:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/akonadi-mime.spec') ||
          contains(inputs.specfiles, '/akonadi-mime.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-server
      - changed-files
      - kmime
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/akonadi-mime/akonadi-mime.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  akonadi-search:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/akonadi-search.spec') ||
          contains(inputs.specfiles, '/akonadi-search.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-mime
      - akonadi-server
      - changed-files
      - kmime
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/akonadi-search/akonadi-search.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  akonadi-server:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/akonadi-server.spec') ||
          contains(inputs.specfiles, '/akonadi-server.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kaccounts-integration
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/akonadi-server/akonadi-server.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  baloo-widgets:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/baloo-widgets.spec') ||
          contains(inputs.specfiles, '/baloo-widgets.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/baloo-widgets/baloo-widgets.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  calendarsupport:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/calendarsupport.spec') ||
          contains(inputs.specfiles, '/calendarsupport.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-calendar
      - akonadi-server
      - changed-files
      - kcalutils
      - kidentitymanagement
      - kmime
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/calendarsupport/calendarsupport.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  eventviews:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/eventviews.spec') ||
          contains(inputs.specfiles, '/eventviews.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-calendar
      - akonadi-server
      - calendarsupport
      - changed-files
      - kcalutils
      - kmime
      - libkdepim
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/eventviews/eventviews.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  grantleetheme:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/grantleetheme.spec') ||
          contains(inputs.specfiles, '/grantleetheme.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/grantleetheme/grantleetheme.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  incidenceeditor:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/incidenceeditor.spec') ||
          contains(inputs.specfiles, '/incidenceeditor.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-calendar
      - akonadi-mime
      - akonadi-server
      - calendarsupport
      - changed-files
      - eventviews
      - kcalutils
      - kidentitymanagement
      - kldap
      - kmime
      - kpimtextedit
      - libkdepim
      - pimcommon
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/incidenceeditor/incidenceeditor.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kaccounts-integration:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kaccounts-integration.spec') ||
          contains(inputs.specfiles, '/kaccounts-integration.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kaccounts-integration/kaccounts-integration.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kaddressbook:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kaddressbook.spec') ||
          contains(inputs.specfiles, '/kaddressbook.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-contacts
      - akonadi-search
      - akonadi-server
      - changed-files
      - grantleetheme
      - kldap
      - kontactinterface
      - libkdepim
      - pimcommon
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kaddressbook/kaddressbook.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kcalutils:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kcalutils.spec') ||
          contains(inputs.specfiles, '/kcalutils.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kidentitymanagement
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kcalutils/kcalutils.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kdegraphics-mobipocket:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kdegraphics-mobipocket.spec') ||
          contains(inputs.specfiles, '/kdegraphics-mobipocket.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kdegraphics-mobipocket/kdegraphics-mobipocket.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  khealthcertificate:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/khealthcertificate.spec') ||
          contains(inputs.specfiles, '/khealthcertificate.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/khealthcertificate/khealthcertificate.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kidentitymanagement:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kidentitymanagement.spec') ||
          contains(inputs.specfiles, '/kidentitymanagement.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kpimtextedit
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kidentitymanagement/kidentitymanagement.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kimap:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kimap.spec') ||
          contains(inputs.specfiles, '/kimap.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kmime
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kimap/kimap.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kitinerary:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kitinerary.spec') ||
          contains(inputs.specfiles, '/kitinerary.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kmime
      - kpkpass
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kitinerary/kitinerary.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kldap:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kldap.spec') ||
          contains(inputs.specfiles, '/kldap.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kldap/kldap.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kmailtransport:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kmailtransport.spec') ||
          contains(inputs.specfiles, '/kmailtransport.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - ksmtp
      - libkgapi
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kmailtransport/kmailtransport.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kmbox:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kmbox.spec') ||
          contains(inputs.specfiles, '/kmbox.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kmime
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kmbox/kmbox.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kmime:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kmime.spec') ||
          contains(inputs.specfiles, '/kmime.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kmime/kmime.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kontactinterface:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kontactinterface.spec') ||
          contains(inputs.specfiles, '/kontactinterface.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kontactinterface/kontactinterface.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kopeninghours:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kopeninghours.spec') ||
          contains(inputs.specfiles, '/kopeninghours.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kopeninghours/kopeninghours.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kosmindoormap:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kosmindoormap.spec') ||
          contains(inputs.specfiles, '/kosmindoormap.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kopeninghours
      - kpublictransport
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kosmindoormap/kosmindoormap.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kpimtextedit:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kpimtextedit.spec') ||
          contains(inputs.specfiles, '/kpimtextedit.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kpimtextedit/kpimtextedit.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kpkpass:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kpkpass.spec') ||
          contains(inputs.specfiles, '/kpkpass.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kpkpass/kpkpass.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kpmcore:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kpmcore.spec') ||
          contains(inputs.specfiles, '/kpmcore.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kpmcore/kpmcore.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kpublictransport:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kpublictransport.spec') ||
          contains(inputs.specfiles, '/kpublictransport.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kpublictransport/kpublictransport.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  ksanecore:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/ksanecore.spec') ||
          contains(inputs.specfiles, '/ksanecore.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/ksanecore/ksanecore.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  ksmtp:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/ksmtp.spec') ||
          contains(inputs.specfiles, '/ksmtp.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/ksmtp/ksmtp.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  ktnef:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/ktnef.spec') ||
          contains(inputs.specfiles, '/ktnef.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kcalutils
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/ktnef/ktnef.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kunifiedpush:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kunifiedpush.spec') ||
          contains(inputs.specfiles, '/kunifiedpush.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kunifiedpush/kunifiedpush.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  kweathercore:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/kweathercore.spec') ||
          contains(inputs.specfiles, '/kweathercore.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/kweathercore/kweathercore.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libgravatar:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libgravatar.spec') ||
          contains(inputs.specfiles, '/libgravatar.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libgravatar/libgravatar.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkcddb:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkcddb.spec') ||
          contains(inputs.specfiles, '/libkcddb.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkcddb/libkcddb.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkcompactdisc:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkcompactdisc.spec') ||
          contains(inputs.specfiles, '/libkcompactdisc.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkcompactdisc/libkcompactdisc.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkdcraw:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkdcraw.spec') ||
          contains(inputs.specfiles, '/libkdcraw.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkdcraw/libkdcraw.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkdegames:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkdegames.spec') ||
          contains(inputs.specfiles, '/libkdegames.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkdegames/libkdegames.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkdepim:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkdepim.spec') ||
          contains(inputs.specfiles, '/libkdepim.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkdepim/libkdepim.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkeduvocdocument:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkeduvocdocument.spec') ||
          contains(inputs.specfiles, '/libkeduvocdocument.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkeduvocdocument/libkeduvocdocument.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkexiv2:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkexiv2.spec') ||
          contains(inputs.specfiles, '/libkexiv2.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkexiv2/libkexiv2.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkgapi:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkgapi.spec') ||
          contains(inputs.specfiles, '/libkgapi.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkgapi/libkgapi.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkleo:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkleo.spec') ||
          contains(inputs.specfiles, '/libkleo.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkleo/libkleo.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkmahjongg:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkmahjongg.spec') ||
          contains(inputs.specfiles, '/libkmahjongg.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkmahjongg/libkmahjongg.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libkomparediff2:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libkomparediff2.spec') ||
          contains(inputs.specfiles, '/libkomparediff2.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libkomparediff2/libkomparediff2.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libksane:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libksane.spec') ||
          contains(inputs.specfiles, '/libksane.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - ksanecore
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libksane/libksane.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libksieve:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libksieve.spec') ||
          contains(inputs.specfiles, '/libksieve.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kidentitymanagement
      - kimap
      - kmailtransport
      - kmime
      - libkdepim
      - pimcommon
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libksieve/libksieve.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  libktorrent:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/libktorrent.spec') ||
          contains(inputs.specfiles, '/libktorrent.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/libktorrent/libktorrent.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  mailcommon:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/mailcommon.spec') ||
          contains(inputs.specfiles, '/mailcommon.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-contacts
      - akonadi-mime
      - akonadi-server
      - changed-files
      - kidentitymanagement
      - kmailtransport
      - kmime
      - libkdepim
      - mailimporter
      - messagelib
      - pimcommon
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/mailcommon/mailcommon.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  mailimporter:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/mailimporter.spec') ||
          contains(inputs.specfiles, '/mailimporter.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-mime
      - akonadi-server
      - changed-files
      - kmime
      - pimcommon
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/mailimporter/mailimporter.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  messagelib:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/messagelib.spec') ||
          contains(inputs.specfiles, '/messagelib.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-contacts
      - akonadi-mime
      - akonadi-search
      - akonadi-server
      - changed-files
      - grantleetheme
      - kidentitymanagement
      - kmailtransport
      - kmbox
      - kmime
      - kpimtextedit
      - libgravatar
      - libkdepim
      - libkleo
      - pimcommon
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/messagelib/messagelib.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  mimetreeparser:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/mimetreeparser.spec') ||
          contains(inputs.specfiles, '/mimetreeparser.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - kmbox
      - kmime
      - libkleo
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/mimetreeparser/mimetreeparser.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

  pimcommon:
    if: >-
      ${{
        ! failure() &&
        ! cancelled() &&
        (
          contains(needs.changed-files.outputs.modified_files, '/pimcommon.spec') ||
          contains(inputs.specfiles, '/pimcommon.spec')
        )
      }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - akonadi-contacts
      - akonadi-search
      - akonadi-server
      - changed-files
      - kimap
      - kldap
      - libkdepim
    secrets:
      gpgkey: ${{ secrets.GPGKEY }}
    with:
      spec: apps/pimcommon/pimcommon.spec
      deps: ${{ toJson(needs) }}
      additional_packages: kf6-srpm-macros
      abidiff: ${{ inputs.abidiff }}

