name: Create repo

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'unstable'
        type: choice
        options:
          - beta
          - unstable

concurrency:
    group: repo-publish
    cancel-in-progress: true

jobs:
  repo:
    runs-on: ubuntu-latest
    container: ghcr.io/solopasha/kde6-copr/buildroot:latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up ORAS
        uses: oras-project/setup-oras@8d34698a59f5ffe24821f0b48ab62a3de8b64b20

      - name: Download packages
        run: |
          mapfile -t packages < <(yq -r '.jobs | keys[]' < .github/workflows/packages.yml | sort -u | grep -v 'changed-files')
          curl -LO -Ss https://github.com/${{ github.repository }}/releases/download/${{ inputs.branch }}/packages.txt || :
          download_package() {
            version="$(oras manifest fetch ghcr.io/${{ github.repository }}/$1:latest-${{ inputs.branch }} | jq -r '.annotations."rpm.version"')"
            if [[ -f "packages.txt" ]]; then
              if grep -q "$1-$version" packages.txt; then
                exit 0
              fi
            fi
            oras pull "ghcr.io/${{ github.repository }}/$1:latest-${{ inputs.branch }}" -o packages
          }
          export -f download_package
          parallel --halt now,fail=1 download_package ::: "${packages[@]}"

      - name: Createrepo
        run: |
          mkdir -p repo/unstable{,-debuginfo} repo/beta{,-debuginfo}
          mv ./packages/*/*debuginfo-*.rpm repo/${{ inputs.branch }}-debuginfo
          mv ./packages/*/*debugsource-*.rpm repo/${{ inputs.branch }}-debuginfo
          mv ./packages/*/*.rpm repo/${{ inputs.branch }}
          rename -v '~' '_' repo/*/*.rpm > /dev/null || :
          rename -v '^' '_' repo/*/*.rpm > /dev/null || :
          createrepo_c -u https://github.com/${{ github.repository }}/releases/download/${{ inputs.branch }} repo/${{ inputs.branch }}
          createrepo_c -u https://github.com/${{ github.repository }}/releases/download/${{ inputs.branch }}-debuginfo repo/${{ inputs.branch }}-debuginfo
          if curl -f -Ss https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ inputs.branch }}/repodata/repomd.xml > /dev/null; then
            mergerepo_c \
              --repo repo/${{ inputs.branch }} \
              --repo https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ inputs.branch }}/
            mergerepo_c \
              -o merged_repo-debuginfo \
              --repo repo/${{ inputs.branch }}-debuginfo \
              --repo https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ inputs.branch }}-debuginfo/
            rm -rf repo/${{ inputs.branch }}/repodata repo/${{ inputs.branch }}-debuginfo/repodata
            mv merged_repo/repodata repo/${{ inputs.branch }}/repodata
            mv merged_repo-debuginfo/repodata repo/${{ inputs.branch }}-debuginfo/repodata
            repodiff -q --refresh \
              --repofrompath=o,https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ inputs.branch }}/ \
              --repofrompath=n,repo/${{ inputs.branch }}/ \
              --repo-old=o --repo-new=n --simple > repodiff
            cat repodiff
            {
              echo "## Added packages"
              grep "^Added package" repodiff | sed -E 's/^Added package  *: */- /'

              echo -e "\n## Removed packages"
              grep "^Removed package" repodiff | sed -E 's/^Removed package  *: */- /'

              echo -e "\n## Modified packages"
              grep -- "->" repodiff | sed -E 's/^(.*) -> (.*)$/- **\1** → **\2**/'

              echo -e "\n## Summary"
              grep "^Summary" -A3 repodiff | sed '1d'
            } >> $GITHUB_STEP_SUMMARY
          fi
          dnf -q \
            --repofrompath='solopasha,repo/${{ inputs.branch }}' \
            --repo=solopasha rq --qf '%{source_name}-%{version}-%{release}\n' | sort -u > repo/${{ inputs.branch }}/packages.txt

      - name: Repoclosure
        run: |
          dnf repoclosure \
            --repofrompath=n,repo/${{ inputs.branch }}/ \
            --check n --newest

          dnf repoclosure \
            --repofrompath=n,repo/${{ inputs.branch }}/ \
            --check n --newest --best

      - name: Createrepo for another branch
        run: |
          if [[ "${{ inputs.branch }}" == "unstable" ]]; then
            another_branch="beta"
          else
            another_branch="unstable"
          fi
          if ! oras pull "ghcr.io/${{ github.repository }}/repodata:latest-${another_branch}"; then
            createrepo_c repo/${another_branch}
            createrepo_c repo/${another_branch}-debuginfo
          fi

      - name: Repofiles
        run: |
          cat << 'EOF' > repo/unstable/${{ github.event.repository.name }}-unstable.repo
          [${{ github.event.repository.name }}:unstable]
          name=${{ github.repository }} - unstable branch
          baseurl=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/unstable/
          type=rpm-md
          skip_if_unavailable=True
          gpgcheck=1
          gpgkey=https://raw.githubusercontent.com/solopasha/kde6-copr/refs/heads/unstable/RPM-GPG-KEY-solopasha
          repo_gpgcheck=0
          enabled=1
          enabled_metadata=1
          metadata_expire=6h

          [${{ github.event.repository.name }}:unstable-debuginfo]
          name=${{ github.repository }} - unstable branch - debuginfo
          baseurl=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/unstable-debuginfo/
          type=rpm-md
          skip_if_unavailable=True
          gpgcheck=1
          gpgkey=https://raw.githubusercontent.com/solopasha/kde6-copr/refs/heads/unstable/RPM-GPG-KEY-solopasha
          repo_gpgcheck=0
          enabled=0
          enabled_metadata=0
          metadata_expire=6h
          EOF

          cat << 'EOF' > repo/beta/${{ github.event.repository.name }}-beta.repo
          [${{ github.event.repository.name }}:beta]
          name=${{ github.repository }} - beta branch
          baseurl=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/beta/
          type=rpm-md
          skip_if_unavailable=True
          gpgcheck=1
          gpgkey=https://raw.githubusercontent.com/solopasha/kde6-copr/refs/heads/unstable/RPM-GPG-KEY-solopasha
          repo_gpgcheck=0
          enabled=1
          enabled_metadata=1
          metadata_expire=6h

          [${{ github.event.repository.name }}:beta-debuginfo]
          name=${{ github.repository }} - beta branch - debuginfo
          baseurl=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/beta-debuginfo/
          type=rpm-md
          skip_if_unavailable=True
          gpgcheck=1
          gpgkey=https://raw.githubusercontent.com/solopasha/kde6-copr/refs/heads/unstable/RPM-GPG-KEY-solopasha
          repo_gpgcheck=0
          enabled=0
          enabled_metadata=0
          metadata_expire=6h
          EOF

      - name: Upload RPMs
        env:
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.event.repository.name }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          git config --global --add safe.directory '*'
          mapfile -t files < <(find ./repo/${{ inputs.branch }} -type f ! -name '*.xml.zst' ! -name '*.xml')
          mapfile -t files_debug < <(find ./repo/${{ inputs.branch }}-debuginfo -type f ! -name '*.xml.zst' ! -name '*.xml')
          gh release view ${{ inputs.branch }} &>/dev/null || gh release create ${{ inputs.branch }} || :
          gh release view ${{ inputs.branch }}-debuginfo &>/dev/null || gh release create ${{ inputs.branch }}-debuginfo || :
          TAG="${{ inputs.branch }}" bash upload_to_release.sh "${files[@]}"
          TAG="${{ inputs.branch }}-debuginfo" bash upload_to_release.sh "${files_debug[@]}"
          rm -f repo/${{ inputs.branch }}/*.rpm
          rm -f repo/${{ inputs.branch }}-debuginfo/*.rpm

      - name: Upload repodata to ghcr
        run: |
          oras login ghcr.io --password "${{ secrets.GITHUB_TOKEN }}" -u "${{ github.actor }}"
          oras push ghcr.io/${{ github.repository }}/repodata:latest-${{ inputs.branch }} repo/${{ inputs.branch }}/repodata repo/${{ inputs.branch }}-debuginfo/repodata

      - name: Upload repodata to artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: repo/

  pages:
    needs: repo
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
